### ISSUE TITLE
Cannot compile release aerospike-client-c-3.1.25 coming from tar.gz archive

### ISSUE THREAD

**Issue by VictorDegliame** [aerospike/aerospike-client-c#29]
Hi,

I downloaded the tar.gz archive for the release 3.1.25 with wget but because it does not contain a .git folder I cannot execute `git submodule update --init` and thus compile the project. Is it possible to add this folder in the release?

I did it by hand and the compilation worked.

Also, `make package` does not work on Ubuntu 14.04: "Invalid platform ubuntu14.04". Maybe it is expected.

Thanks,
Victor

**Comment by BrianNichols** [comment]
The tar archive from www.aerospike.com is just a snapshot of the source code.  You don't need to run "git submodule update --init" in order to build the snapshot.  Just run "make".

We host a separate github repository at https://github.com/aerospike/aerospike-client-c.  You can clone this repository onto your local machine to gain git compatibility.
