### ISSUE TITLE
Libevent support

### ISSUE THREAD

**Issue by maxim-ky** [aerospike/aerospike-client-c#34]
Hello, guys!

Do you plan to support libevent-based async engine? It would be very nice, because libevent is as popular as libev or libuv.
Now I use that one http://www.aerospike.com/docs/client/libevent/ , but it's closed-source and it looks a little bit outdated/frozen.

Regards

**Comment by BrianNichols** [comment]
libevent is under consideration.  No decision has been made yet.

**Comment by maxim-ky** [comment]
Thank you for the information.
Is there some way to know your future decision? It would be perfect to have some kind of notification :)

**Comment by BrianNichols** [comment]
We will announce the decision in this thread.

**Comment by maxim-ky** [comment]
Thank you!

**Comment by maxim-ky** [comment]
Hi guys,

Here is a patch to support libevent https://github.com/aerospike/aerospike-client-c/pull/50
It seems to be working ok, at least it passes all the tests :)

**Comment by BrianNichols** [comment]
No, it's not your fault.  The remote libev library was moved and install_libev needs to be changed to reflect that.  It will be fixed in the next release.

There hasn't been movement on libevent support in the past because libev is considered a superior framework and customers would be better served by using libev.  There is, however, legacy reasons for maybe using libevent.  In that view, we will review your pull request for inclusion into the C client.

We are currently busy with other projects, so official libevent support will not happen immediately.

**Comment by ramrengaswamy** [comment]
@BrianNichols Any sense of when the official libevent support will be released ?

**Comment by BrianNichols** [comment]
We plan to release the C client this week.

**Comment by BrianNichols** [comment]
C client 4.1.3 has been released with libevent support.
