### ISSUE TITLE
No deep copy of `as_config_s` in `aerospike_init` after making `hosts` member as a pointer instead of C-array in commit 6b5a82f8

### ISSUE THREAD

**Issue by eldar-activevideo** [aerospike/aerospike-client-c#43]
After recent changes in [6b5a82f8](https://github.com/aerospike/aerospike-client-c/commit/6b5a82f8662b92072d9ccfafd6ea987498153cbf) in file **as_config.h**, member **hosts** changed from this:

`as_config_host hosts[AS_CONFIG_HOSTS_SIZE];`

to this:

`as_vector* hosts;`

But **aerospike_init** copies config using simple **memcpy**:

```
static aerospike*
aerospike_defaults(aerospike* as, bool free, as_config* config)
{
    as->_free = free;
    as->cluster = NULL;
    if ( config != NULL ) {
        memcpy(&as->config, config, sizeof(as_config));
    }
```

```
aerospike*
aerospike_init(aerospike* as, as_config* config)
{
    if ( !as ) return as;
    return aerospike_defaults(as, false, config);
}
```
As a result of that two places have the same pointer to **hosts** which may lead to **double free** due to diluting ownership of pointer to **hosts**.

This is effectively happen when **as_cluster_create** destroys **hosts**:

```
// Destroy config hosts vector after transferring data to cluster.
as_vector_destroy(config->hosts);
````

(this change from the same commit).

Then we destroy (in our library) separately our config (which is supposedly deeply copied) after we call **aerospike_init**. And here crash happens (in our library).

We will do workaround about this case in our library. But I think it's also should be fixed in your library as well (i.e. don't use **memcpy** to copy config in **aerospike_defaults**).

Also, I suggest **as_vector_destroy** in **as_cluster_create** should be replaced by some specific destructor similar to how **hosts** destroyed in **as_config_destroy** since it's not just **as_vector_destroy**.

**Comment by djc** [comment]
Ping! This seems like an obvious bug in the client C libraries, please review the material.

**Comment by BrianNichols** [comment]
We will fix this bug in the next release.

**Comment by djc** [comment]
@BrianNichols that's good to hear. Do you have an approximate ETA for this?

**Comment by BrianNichols** [comment]
The C client is released approximately once per month, so it should be released by the end of this month.

In the meantime, don't call as_config_destroy() because as_cluster_create() transfers ownership of hosts and cluster_id to as_cluster.  The client will not leak memory if as_cluster_create() is successful.

**Comment by BrianNichols** [comment]
This problem will be fixed by making as_config_destroy() a private function.  First, all dynamically allocated as_config variables will be copied using setter functions.  When aerospike_init() is called, the client will assume ownership of all config fields.  When aerospike_destroy() is called, as_config_destroy() will be internally called.

The user should not call as_config_destroy() directly.

**Comment by eldar-activevideo** [comment]
Thank you for update!

I suggest to make transferring of ownership in **aerospike_init** more explicit for user because currently it's not obvious that **aerospike_init** takes ownership of **as_config** object.

**Comment by BrianNichols** [comment]
C client 4.1.1 has been released.

http://www.aerospike.com/download/client/c/4.1.1/
