### ISSUE TITLE
Pkg-config configuration is not included with the tarballs

### ISSUE THREAD

**Issue by vertexclique** [aerospike/aerospike-client-c#52]
`pc` file is not present in both `macos` and `linux` environments.

**Comment by BrianNichols** [comment]
Since libaerospike cflags and libs depend on the event framework, that would require 4 different pc files (libaerospike.pc, libaerospike-libev.pc, libaerospike-libuv.pc, libaerospike-libevent.pc) for each platform.

Do you think it would still be useful to include these pc files given this complexity?

The alternative is to just copy the cflags and libs used when compiling the pre-packaged examples.

**Comment by vertexclique** [comment]
> The alternative is to just copy the cflags and libs used when compiling the packaged examples.

My aim is not compiling against the library. Problem is in multiple systems paths are changeable and generating a FFI binding in yet another programming language is becoming cumbersome.

Meanwhile some of the header files also not included with the tarballs. Which makes the FFI binding generation even more harder. So in that scenario which directory should be scanned? There are multiple directories with different headers `aerospike`, `citrusleaf` (which doesn't have `cf_byte_order.h` for example) and `aerospike/ck` those directories are incomplete with headers and there is no reliable rule to find which header is where.

If you provide an interface for finding header and lib location it will be really useful. I mentioned this lack of header problem in https://github.com/aerospike/aerospike-client-c/issues/37#issuecomment-270544044 .

**Comment by BrianNichols** [comment]
`cf_byte_order.h` should have been made a public header file.  This will be fixed in the next release.

Other header files are not included in the packages (rpm,deb) because they are private to the library.

The public headers are located in one of the following places in the source code repository:

```
src/include
modules/common/src/include
```

Do you want "pc" files for the source code repository or the package install locations?
Can you issue a pull request to avoid any ambiguity?

**Comment by BrianNichols** [comment]
C client 4.1.4 has been released:

http://www.aerospike.com/download/client/c/4.1.4/
