### ISSUE TITLE
libev and libevent build speed comparison.

### ISSUE THREAD

**Issue by aknovikov** [aerospike/aerospike-client-c#65]
Hello. The performance test for building a utility benchmarks with the libev library gave the following results:
time ./benchmarks_libev -h 127.0.0.1 -p 3000 -a -n test -s newtest -k 1000000 -o B:256 -w RU,50 -t 3000000 -T 10 -z 1
real	0m26.936s
user	0m5.948s
sys	0m20.984s

However, the assembly with the libevent library is much slower:
time ./benchmarks_libevent -h 127.0.0.1 -p 3000 -a -n test -s newtest -k 1000000 -o B:256 -w RU,50 -t 3000000 -T 10 -z 1
real	0m36.975s
user	0m8.884s
sys	0m27.948s

Why such a big time difference?

**Comment by BrianNichols** [comment]
I also get similar results regarding libev performance over libevent.  I don't fully understand why the descrepancy is so wide.  

It might be related to our use of `evthread_use_pthreads()` or `evthread_make_base_notifiable()`.  We do allow multiple event loop threads, but each event loop never directly calls libevent routines from another event loop.  Commands passed between event loops are always sent by a thread-safe queue, so enabling thread-safety in libevent may be unnecessary.  The documentation is not clear about this, so we decided to be safe and enable thread-safety for libevent.

libev doesn't have this thread safety mode because every libev call (except ev_async_send()) must be made in it's event loop thread.  libev is much simpler because of it's single threaded nature.

libev was our original event library for the new C client and has received the most tuning and development time.  We have always recommended libev as the preferred event library for Aerospike.  We also chose libev when implementing our XDR product (cross data center replication).  XDR requires the maximum performance possible.
