### ISSUE TITLE
event_base_dispatch will trigger core dump in Aerospike Client when high pressure

### ISSUE THREAD

**Issue by earnestzhao** [aerospike/aerospike-client-c#86]
Dear developers,

This code below causes a core dump which is hard to position.
#if LIBEVENT_VERSION_NUMBER < 0x02010000
    int status = event_base_dispatch(loop);
#else
    int status = event_base_loop(loop, EVLOOP_NO_EXIT_ON_EMPTY);
#endif

Our libevent version is 2.0.22. So, the program runs with "event_base_dispatch". When 100000 requests came, it triggered core dump. Then, we defined a macro -DLIBEVENT_VERSION_NUMBER=40000000 which is larger than 0x02010000, and the core dump disappeared.

I want to ask you guys about the design. "event_base_loop" has already existed in 2.0.22. But it seems that you guys specify the usage of "event_base_loop" only when libevent version is bigger than 2.1. Could you tell me the reason for this condition LIBEVENT_VERSION_NUMBER < 0x02010000?

I am looking forward and very appreciate to your reply about this question.

Thanks,
Earnest Zhao

**Comment by BrianNichols** [comment]
From the libevent documentation:
```
The event_base_dispatch() call is the same as event_base_loop(), with no flags set. 
```
The flag EVLOOP_NO_EXIT_ON_EMPTY does not exist in version 2.0.22, so there is no reason to set any flags.  Instead, version 2.0.22 uses event_base_add_virtual() to prevent exiting from an empty event loop.

Your program's core dump is likely because you didn't throttle the command queue.  You can throttle like this example:

https://www.aerospike.com/docs/client/c/usage/async.html

Another way is to define `max_commands_in_process` and `max_commands_in_queue`.
```
as_policy_event p;
as_policy_event_init(&p);

// Limit event loop to process max 50 commands concurrently.
p.max_commands_in_process = 50;

// Place a hard limit on delay queue.  If this limit is reached, the command
// will be rejected.
p.max_commands_in_queue = 10000;

as_error err;
as_create_event_loops(&err, &p, 1, NULL);
```

**Comment by earnestzhao** [comment]
Dear Brian,

This issue has been solved after we got your advice. Thank you very much.


Best Regards,
Earnest Zhao
